name: minerl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - numpy
    - torch
    - gym
    - dill
    - scikit-learn
    - h5py
    - tqdm
