name: minerl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - py-opencv
  - cudatoolkit=10.1
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - numpy
    - dill
    - scikit-learn
    - h5py
    - tqdm
    - torch==1.7.0
