name: minerl
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - py-opencv
  - pytorch
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - numpy
    - dill
    - scikit-learn
    - h5py
    - tqdm
